name: Run Django App Steps

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Django
        run: |
          python -m pip install --upgrade pip
          pip install django==3.2

      - name: Run migrations
        working-directory: ./djangotodo-ci-cd/todoApp
        run: python manage.py migrate

      - name: Run server (test only)
        working-directory: ./djangotodo-ci-cd/todoApp
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10
          curl -f http://127.0.0.1:8000 || (echo "Server did not start!" && exit 1)
