name: CodeQL Scan → Django Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * 1'  # weekly scheduled scan

jobs:
  codeql:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild (Python)
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build:
    name: Run Django App Steps
    needs: codeql  # ✅ run only after CodeQL completes successfully
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Django
        run: |
          python -m pip install --upgrade pip
          pip install django==3.2

      - name: Run migrations
        working-directory: ./todoApp
        run: python manage.py migrate

      - name: Run server (test only)
        working-directory: ./todoApp
        run: |
          nohup python manage.py runserver 0.0.0.0:8000 &
          sleep 10
          curl -f http://127.0.0.1:8000/todos || (echo "Server did not start!" && exit 1)
